apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i1qv9j0aa-dotnet-basic
  janus-idp.io/tekton: i1qv9j0aa-dotnet-basic
  backstage.io/kubernetes-id: i1qv9j0aa-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: i1qv9j0aa-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
